# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOWED_ORIGINS)%']
        allow_methods: ['POST', 'GET', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['%env(CORS_ALLOWED_ORIGINS)%']
            allow_methods: ['POST', 'GET', 'OPTIONS']
            allow_headers: ['Content-Type']
            max_age: 3600